DROP TABLE IF EXISTS bills;

CREATE TABLE IF NOT EXISTS bills
ROW FORMAT DELIMITED
	FIELDS TERMINATED BY ',';

LOAD DATA INPATH 'hiveInput/example.txt'
OVERWRITE INTO TABLE bills;

SELECT *
FROM bills